name: jahesh_up_backend
version: 1.0.0
description: A new Get Server application.
environment:
  sdk: '>=3.1.0-65.0.dev <4.0.0'

#isar_version: &isar_version ^4.0.0-dev.14 # define the version to be used
isar_version: &isar_version 3.1.0+1 # define the version to be used

dependencies:
  dartx: ^1.2.0
  password_strength: ^0.2.0

#  path_provider_windows: ^2.2.1
#  path_provider: ^2.1.0
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.3
  json_annotation: ^4.8.0
  get_server: 1.2.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  json_serializable: ^6.6.0
  build_runner: any
  isar_generator: *isar_version
  pedantic: 1.11.1
  test: 1.24.6

